server:
  port: 18081

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sca-provider
  consumer:
    check: false

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/yuhb-test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: danielyu0629
  cloud:
    loadbalancer:
      ribbon:
        enabled: false


mybatis:
  mapper-locations: classpath:mapper/*.xml


seata:
  tx-service-group: sca-customer-seata-tx-service-group
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.2.16
  config:
    type: nacos
    nacos:
      server-addr: 192.168.2.16


loadbalancer:
  client:
    name: sca-provider